version: '3.3'
services:
  db:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - .db/:/var/lib/postgresql/data
  
  api:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - 8000:8000
 

  

  